baseURL = "https://hung186it.github.io/jomulongthanh/"
languageCode = "en-us"
title = "JoMu Textile Vietnam Co., Ltd."

theme = "hero"


  [params.homepage_meta_tags]
    meta_description = "Jomu Textiles Vietnam, a denim fabric mill located near Ho Chi Minh City, Vietnam."
    meta_og_title = "Jomu Textiles Vietnam Co, Ltd."
    meta_og_type = "website"
    meta_og_url = "https://www.jomu.com.vn"
    meta_og_image = "https://www.jomu.com.vn/images/tn.png"
    meta_og_description = "Jomu Textiles Vietnam, a denim fabric mill located near Ho Chi Minh City, Vietnam."
    [permalinks]
      post = "/:year/:month/:day/:slug/"
      pages = "/:filename/"
      [sitemap]
      ChangeFreq = ""
      Filename = "sitemap.xml"
      Priority = "-1"
